# Generated by Django 5.2 on 2025-06-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_studycapsule_correct_answer_studycapsule_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studycapsule',
            name='correct_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
