# Generated by Django 5.1.4 on 2024-12-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelajaran', models.CharField(blank=True, max_length=100, null=True)),
                ('hari', models.CharField(blank=True, max_length=20, null=True)),
                ('jam_mulai', models.TimeField(default='00:00:00')),
                ('jam_selesai', models.TimeField(default='01:00:00')),
            ],
        ),
        migrations.DeleteModel(
            name='JadwalPelajaran',
        ),
    ]
